### ISSUE TITLE
Getting connection error while running the backend

### ISSUE THREAD

**Issue by nihalmpatel** [forkdelta/backend-replacement#101]
**Error log while running : docker-compose up**

```
WARNING: The ALLOWED_ORIGIN_SUFFIXES variable is not set. Defaulting to a blank string.
backend-replacement_postgres_1 is up-to-date
backend-replacement_redis_1 is up-to-date
Starting backend-replacement_ticker_1              ... done
Starting backend-replacement_websocket_server_1    ... done
Starting backend-replacement_contract_observer_1   ... done
Starting backend-replacement_huey_consumer_1       ... done
Starting backend-replacement_etherdelta_observer_1 ... done
Attaching to backend-replacement_postgres_1, backend-replacement_redis_1, backend-replacement_ticker_1, backend-replacement_websocket_server_1, backend-replacement_contract_observer_1, backend-replacement_huey_consumer_1, backend-replacement_etherdelta_observer_1
postgres_1             | The files belonging to this database system will be owned by user "postgres".
postgres_1             | This user must also own the server process.
postgres_1             |
postgres_1             | The database cluster will be initialized with locale "en_US.utf8".
postgres_1             | The default database encoding has accordingly been set to "UTF8".
postgres_1             | The default text search configuration will be set to "english".
postgres_1             |
postgres_1             | Data page checksums are disabled.
postgres_1             |
postgres_1             | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1             | creating subdirectories ... ok
postgres_1             | selecting default max_connections ... 100
postgres_1             | selecting default shared_buffers ... 128MB
postgres_1             | selecting dynamic shared memory implementation ... posix
postgres_1             | creating configuration files ... ok
postgres_1             | running bootstrap script ... ok
postgres_1             | sh: locale: not found
postgres_1             | 2018-07-12 12:43:44.877 UTC [24] WARNING:  no usable system locales were found
postgres_1             | performing post-bootstrap initialization ... ok
postgres_1             | syncing data to disk ... ok
postgres_1             |
postgres_1             | WARNING: enabling "trust" authentication for local connections
postgres_1             | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1             | --auth-local and --auth-host, the next time you run initdb.
postgres_1             |
postgres_1             | Success. You can now start the database server using:
postgres_1             |
postgres_1             |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1             |
postgres_1             | waiting for server to start....2018-07-12 12:43:46.859 UTC [28] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1             | 2018-07-12 12:43:46.899 UTC [29] LOG:  database system was shut down at 2018-07-12 12:43:46 UTC
postgres_1             | 2018-07-12 12:43:46.902 UTC [28] LOG:  database system is ready to accept connections
postgres_1             |  done
postgres_1             | server started
postgres_1             | CREATE DATABASE
postgres_1             |
postgres_1             | CREATE ROLE
postgres_1             |
postgres_1             |
redis_1                | 1:C 12 Jul 12:43:41.388 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                | 1:C 12 Jul 12:43:41.389 # Redis version=4.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                | 1:C 12 Jul 12:43:41.390 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                | 1:M 12 Jul 12:43:41.391 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1                | 1:M 12 Jul 12:43:41.393 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
redis_1                | 1:M 12 Jul 12:43:41.394 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
redis_1                | 1:M 12 Jul 12:43:41.397 * Running mode=standalone, port=6379.
redis_1                | 1:M 12 Jul 12:43:41.399 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1                | 1:M 12 Jul 12:43:41.399 # Server initialized
redis_1                | 1:M 12 Jul 12:43:41.399 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                | 1:M 12 Jul 12:43:41.399 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                | 1:M 12 Jul 12:43:41.399 * Ready to accept connections
redis_1                | 1:signal-handler (1531399471) Received SIGTERM scheduling shutdown...
redis_1                | 1:M 12 Jul 12:44:31.416 # User requested shutdown...
redis_1                | 1:M 12 Jul 12:44:31.416 * Saving the final RDB snapshot before exiting.
redis_1                | 1:M 12 Jul 12:44:31.419 * DB saved on disk
redis_1                | 1:M 12 Jul 12:44:31.419 # Redis is now ready to exit, bye bye...
redis_1                | 1:C 12 Jul 12:55:26.706 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                | 1:C 12 Jul 12:55:26.707 # Redis version=4.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                | 1:C 12 Jul 12:55:26.707 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                | 1:M 12 Jul 12:55:26.716 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1                | 1:M 12 Jul 12:55:26.716 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
redis_1                | 1:M 12 Jul 12:55:26.716 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
redis_1                | 1:M 12 Jul 12:55:26.718 * Running mode=standalone, port=6379.
redis_1                | 1:M 12 Jul 12:55:26.719 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1                | 1:M 12 Jul 12:55:26.719 # Server initialized
redis_1                | 1:M 12 Jul 12:55:26.719 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                | 1:M 12 Jul 12:55:26.719 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                | 1:M 12 Jul 12:55:26.720 * DB loaded from disk: 0.000 seconds
redis_1                | 1:M 12 Jul 12:55:26.720 * Ready to accept connections
redis_1                | 1:C 12 Jul 13:02:24.774 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                | 1:C 12 Jul 13:02:24.775 # Redis version=4.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                | 1:C 12 Jul 13:02:24.775 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                | 1:M 12 Jul 13:02:24.785 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1                | 1:M 12 Jul 13:02:24.785 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
redis_1                | 1:M 12 Jul 13:02:24.785 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
redis_1                | 1:M 12 Jul 13:02:24.786 * Running mode=standalone, port=6379.
redis_1                | 1:M 12 Jul 13:02:24.787 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
postgres_1             | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1             |
postgres_1             | 2018-07-12 12:43:47.319 UTC [28] LOG:  received fast shutdown request
postgres_1             | waiting for server to shut down....2018-07-12 12:43:47.322 UTC [28] LOG:  aborting any active transactions
postgres_1             | 2018-07-12 12:43:47.323 UTC [28] LOG:  worker process: logical replication launcher (PID 35) exited with exit code 1
postgres_1             | 2018-07-12 12:43:47.323 UTC [30] LOG:  shutting down
postgres_1             | 2018-07-12 12:43:47.336 UTC [28] LOG:  database system is shut down
postgres_1             |  done
postgres_1             | server stopped
postgres_1             |
postgres_1             | PostgreSQL init process complete; ready for start up.
postgres_1             |
postgres_1             | 2018-07-12 12:43:47.427 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1             | 2018-07-12 12:43:47.427 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1             | 2018-07-12 12:43:47.431 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1             | 2018-07-12 12:43:47.445 UTC [41] LOG:  database system was shut down at 2018-07-12 12:43:47 UTC
postgres_1             | 2018-07-12 12:43:47.449 UTC [1] LOG:  database system is ready to accept connections
postgres_1             | 2018-07-12 12:43:47.510 UTC [48] ERROR:  relation "tickers" does not exist at character 48
postgres_1             | 2018-07-12 12:43:47.510 UTC [48] STATEMENT:
postgres_1             |                        SELECT *
postgres_1             |                        FROM tickers
postgres_1             |
postgres_1             | 2018-07-12 12:43:52.462 UTC [48] ERROR:  relation "orders" does not exist at character 40
postgres_1             | 2018-07-12 12:43:52.462 UTC [48] STATEMENT:
postgres_1             |                    SELECT *
postgres_1             |                    FROM orders
postgres_1             |                    WHERE ("date" >= $1 OR "updated" >= $1) AND ("token_give" = $2)
postgres_1             |                    ORDER BY updated ASC, date ASC
postgres_1             |
postgres_1             | 2018-07-12 12:43:52.474 UTC [49] ERROR:  relation "trades" does not exist at character 40
postgres_1             | 2018-07-12 12:43:52.474 UTC [49] STATEMENT:
postgres_1             |                    SELECT *
postgres_1             |                    FROM trades
postgres_1             |                    WHERE ("date" > $1) AND ("token_give" = $2 OR "token_get" = $2)
postgres_1             |                    ORDER BY block_number DESC, date DESC
postgres_1             |
postgres_1             | 2018-07-12 12:43:52.475 UTC [50] ERROR:  relation "transfers" does not exist at character 40
postgres_1             | 2018-07-12 12:43:52.475 UTC [50] STATEMENT:
postgres_1             |                    SELECT *
postgres_1             |                    FROM transfers
postgres_1             |                    WHERE ("date" > $1)
postgres_1             |                    ORDER BY block_number DESC, date DESC
postgres_1             |
postgres_1             | 2018-07-12 12:44:41.123 UTC [1] LOG:  received smart shutdown request
postgres_1             | 2018-07-12 12:44:41.128 UTC [1] LOG:  worker process: logical replication launcher (PID 47) exited with exit code 1
postgres_1             | 2018-07-12 12:44:41.128 UTC [42] LOG:  shutting down
postgres_1             | 2018-07-12 12:44:41.159 UTC [1] LOG:  database system is shut down
postgres_1             | 2018-07-12 12:55:26.802 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1             | 2018-07-12 12:55:26.802 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1             | 2018-07-12 12:55:26.810 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1             | 2018-07-12 12:55:26.832 UTC [17] LOG:  database system was shut down at 2018-07-12 12:44:41 UTC
postgres_1             | 2018-07-12 12:55:26.835 UTC [1] LOG:  database system is ready to accept connections
postgres_1             | 2018-07-12 13:02:24.884 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1             | 2018-07-12 13:02:24.884 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1             | 2018-07-12 13:02:24.890 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1             | 2018-07-12 13:02:24.917 UTC [17] LOG:  database system was interrupted; last known up at 2018-07-12 12:55:26 UTC
postgres_1             | 2018-07-12 13:02:25.001 UTC [17] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1             | 2018-07-12 13:02:25.005 UTC [17] LOG:  redo starts at 0/15C0E78
postgres_1             | 2018-07-12 13:02:25.019 UTC [17] LOG:  invalid record length at 0/16132E8: wanted 24, got 0
postgres_1             | 2018-07-12 13:02:25.020 UTC [17] LOG:  redo done at 0/16132B0
postgres_1             | 2018-07-12 13:02:25.020 UTC [17] LOG:  last completed transaction was at log time 2018-07-12 12:55:27.702508+00
postgres_1             | 2018-07-12 13:02:25.060 UTC [1] LOG:  database system is ready to accept connections
postgres_1             | 2018-07-12 13:08:37.031 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1             | 2018-07-12 13:08:37.031 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1             | 2018-07-12 13:08:37.035 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
redis_1                | 1:M 12 Jul 13:02:24.788 # Server initialized
redis_1                | 1:M 12 Jul 13:02:24.788 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                | 1:M 12 Jul 13:02:24.788 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                | 1:M 12 Jul 13:02:24.789 * DB loaded from disk: 0.000 seconds
redis_1                | 1:M 12 Jul 13:02:24.789 * Ready to accept connections
redis_1                | 1:signal-handler (1531400848) Received SIGTERM scheduling shutdown...
redis_1                | 1:M 12 Jul 13:07:28.541 # User requested shutdown...
redis_1                | 1:M 12 Jul 13:07:28.541 * Saving the final RDB snapshot before exiting.
redis_1                | 1:M 12 Jul 13:07:28.543 * DB saved on disk
redis_1                | 1:M 12 Jul 13:07:28.543 # Redis is now ready to exit, bye bye...
redis_1                | 1:C 12 Jul 13:08:37.003 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                | 1:C 12 Jul 13:08:37.004 # Redis version=4.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                | 1:C 12 Jul 13:08:37.004 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                | 1:M 12 Jul 13:08:37.006 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1                | 1:M 12 Jul 13:08:37.009 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
redis_1                | 1:M 12 Jul 13:08:37.009 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
redis_1                | 1:M 12 Jul 13:08:37.009 * Running mode=standalone, port=6379.
redis_1                | 1:M 12 Jul 13:08:37.009 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1                | 1:M 12 Jul 13:08:37.009 # Server initialized
redis_1                | 1:M 12 Jul 13:08:37.010 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                | 1:M 12 Jul 13:08:37.010 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                | 1:M 12 Jul 13:08:37.010 * DB loaded from disk: 0.000 seconds
redis_1                | 1:M 12 Jul 13:08:37.010 * Ready to accept connections
redis_1                | 1:C 12 Jul 13:10:17.694 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                | 1:C 12 Jul 13:10:17.694 # Redis version=4.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                | 1:C 12 Jul 13:10:17.694 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                | 1:M 12 Jul 13:10:17.696 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1                | 1:M 12 Jul 13:10:17.702 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
redis_1                | 1:M 12 Jul 13:10:17.702 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
redis_1                | 1:M 12 Jul 13:10:17.703 * Running mode=standalone, port=6379.
redis_1                | 1:M 12 Jul 13:10:17.704 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1                | 1:M 12 Jul 13:10:17.704 # Server initialized
redis_1                | 1:M 12 Jul 13:10:17.704 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                | 1:M 12 Jul 13:10:17.705 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                | 1:M 12 Jul 13:10:17.705 * DB loaded from disk: 0.000 seconds
redis_1                | 1:M 12 Jul 13:10:17.705 * Ready to accept connections
postgres_1             | 2018-07-12 13:08:37.055 UTC [17] LOG:  database system was interrupted; last known up at 2018-07-12 13:07:26 UTC
postgres_1             | 2018-07-12 13:08:37.092 UTC [17] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1             | 2018-07-12 13:08:37.095 UTC [17] LOG:  redo starts at 0/1619220
postgres_1             | 2018-07-12 13:08:37.095 UTC [17] LOG:  invalid record length at 0/16192C8: wanted 24, got 0
postgres_1             | 2018-07-12 13:08:37.095 UTC [17] LOG:  redo done at 0/1619258
postgres_1             | 2018-07-12 13:08:37.108 UTC [1] LOG:  database system is ready to accept connections
postgres_1             | 2018-07-12 13:10:17.783 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1             | 2018-07-12 13:10:17.783 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1             | 2018-07-12 13:10:17.787 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1             | 2018-07-12 13:10:17.837 UTC [17] LOG:  database system was interrupted; last known up at 2018-07-12 13:08:37 UTC
postgres_1             | 2018-07-12 13:10:17.875 UTC [17] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1             | 2018-07-12 13:10:17.880 UTC [17] LOG:  redo starts at 0/1619338
postgres_1             | 2018-07-12 13:10:17.880 UTC [17] LOG:  invalid record length at 0/1619370: wanted 24, got 0
postgres_1             | 2018-07-12 13:10:17.880 UTC [17] LOG:  redo done at 0/1619338
postgres_1             | 2018-07-12 13:10:17.905 UTC [1] LOG:  database system is ready to accept connections
ticker_1               | App.App      INFO     Token list refreshed: 996 tokens.
ticker_1               | services.ticker INFO     993 tokens added to ticker queue
ticker_1               | services.ticker ERROR    Exception while processing token addr=0x006bea43baa3f7a6f765f14f10a1a1b08334ef45
ticker_1               | Traceback (most recent call last):
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
ticker_1               |     (self._dns_host, self.port), self.timeout, **extra_kw)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
ticker_1               |     raise err
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
ticker_1               |     sock.connect(sa)
ticker_1               | ConnectionRefusedError: [Errno 111] Connection refused
ticker_1               |
ticker_1               | During handling of the above exception, another exception occurred:
ticker_1               |
ticker_1               | Traceback (most recent call last):
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
ticker_1               |     chunked=chunked)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
ticker_1               |     conn.request(method, url, **httplib_request_kw)
ticker_1               |   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
ticker_1               |     self._send_request(method, url, body, headers, encode_chunked)
ticker_1               |   File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
ticker_1               |     self.endheaders(body, encode_chunked=encode_chunked)
ticker_1               |   File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
ticker_1               |     self._send_output(message_body, encode_chunked=encode_chunked)
ticker_1               |   File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
ticker_1               |     self.send(msg)
ticker_1               |   File "/usr/local/lib/python3.6/http/client.py", line 964, in send
ticker_1               |     self.connect()
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
ticker_1               |     conn = self._new_conn()
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
ticker_1               |     self, "Failed to establish a new connection: %s" % e)
ticker_1               | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa23b4dd2b0>: Failed to establish a new connection: [Errno 111] Connection refused
ticker_1               |
ticker_1               | During handling of the above exception, another exception occurred:
ticker_1               |
ticker_1               | Traceback (most recent call last):
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
ticker_1               |     timeout=timeout
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
ticker_1               |     _stacktrace=sys.exc_info()[2])
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
ticker_1               |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
ticker_1               | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='138.197.160.134', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa23b4dd2b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ticker_1               |
ticker_1               | During handling of the above exception, another exception occurred:
ticker_1               |
ticker_1               | Traceback (most recent call last):
ticker_1               |   File "/usr/src/app/app/services/ticker.py", line 234, in main
ticker_1               |     await update_ticker(token)
ticker_1               |   File "/usr/src/app/app/services/ticker.py", line 168, in update_ticker
ticker_1               |     current_block = App().web3.eth.blockNumber
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/web3/eth.py", line 92, in blockNumber
ticker_1               |     return self.web3.manager.request_blocking("eth_blockNumber", [])
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/web3/manager.py", line 93, in request_blocking
ticker_1               |     response = self._make_request(method, params)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/web3/manager.py", line 76, in _make_request
ticker_1               |     return request_func(method, params)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 20, in middleware
ticker_1               |     response = make_request(method, params)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 25, in middleware
ticker_1               |     response = make_request(method, params)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/web3/providers/rpc.py", line 52, in make_request
ticker_1               |     **self.get_request_kwargs()
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
ticker_1               |     response = session.post(endpoint_uri, data=data, *args, **kwargs)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 559, in post
ticker_1               |     return self.request('POST', url, data=data, json=json, **kwargs)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
ticker_1               |     resp = self.send(prep, **send_kwargs)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
ticker_1               |     r = adapter.send(request, **kwargs)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
ticker_1               |     raise ConnectionError(e, request=request)
ticker_1               | requests.exceptions.ConnectionError: HTTPConnectionPool(host='138.197.160.134', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa23b4dd2b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
contract_observer_1    | App.App      INFO     Token list refreshed: 996 tokens.
```

**Comment by freeatnet** [comment]
@nihalmpatel You need your own Parity node to run the backend (Parity node is not included in the `docker-compose` setup). You can adjust the URL of the node in `.env` using `HTTP_PROVIDER_URL` and `WS_PROVIDER_URL`. As an option, I've had reasonable success (for testing purposes) with infura nodes, like so:
```
HTTP_PROVIDER_URL=https://mainnet.infura.io/YOUR_API_KEY
WS_PROVIDER_URL=wss://mainnet.infura.io/ws
```

**Comment by nihalmpatel** [comment]
It worked! Thanks.
