### ISSUE TITLE
Etherdelta observer stops abnormally

### ISSUE THREAD

**Issue by nihalmpatel** [forkdelta/backend-replacement#104]
In app/config.py I have following code:
ED_WS_SERVERS = ["wss://<<MY_IP>>:8080/socket.io/?EIO=3&transport=websocket"]

```
websocket_server_1     | websocket_server DEBUG    current_block=6040566
websocket_server_1     | ======== Running on http://0.0.0.0:8080 ========
websocket_server_1     | (Press CTRL+C to quit)
etherdelta_observer_1  | App.App      INFO     Token list refreshed: 42 tokens.
etherdelta_observer_1  | etherdelta_observer INFO     42 tokens added to market queue
etherdelta_observer_1  | Traceback (most recent call last):
etherdelta_observer_1  |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
etherdelta_observer_1  |     "__main__", mod_spec)
etherdelta_observer_1  |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
etherdelta_observer_1  |     exec(code, run_globals)
etherdelta_observer_1  |   File "/usr/src/app/app/services/etherdelta_observer.py", line 222, in <module>
etherdelta_observer_1  |     loop.run_until_complete(asyncio.gather(*tasks))
etherdelta_observer_1  |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
etherdelta_observer_1  |     return future.result()
etherdelta_observer_1  |   File "/usr/src/app/app/services/etherdelta_observer.py", line 194, in main
etherdelta_observer_1  |     ws_url = ED_WS_SERVERS[my_id]
etherdelta_observer_1  | IndexError: list index out of range
websocket_server_1     | websocket_server DEBUG    tickers cache updated
ticker_1               | services.ticker DEBUG    {'token_address': '0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27', 'quote_volume': Decimal('0'), 'base_volume': Decimal('0'), 'last': None, 'ask': None, 'bid': None}
ticker_1               | services.ticker DEBUG    {'token_address': '0xb5a5f22694352c15b00323844ad545abb2b11028', 'quote_volume': Decimal('0'), 'base_volume': Decimal('0'), 'last': None, 'ask': None, 'bid': None}
polarisdex-backend_etherdelta_observer_1 exited with code 1
```

**Comment by nihalmpatel** [comment]
In etherdelta_observer.py NUM_OBSERVERS = 1 solves the issue.
Closes #104

**Comment by nihalmpatel** [comment]
In etherdelta_observer.py setting NUM_OBSERVERS = 1 fixes the issue.

**Comment by freeatnet** [comment]
I'm sorry, I do not have the bandwidth to provide support for individual configuration issues.
