### ISSUE TITLE
Handle ED connection closing errors more gracefully

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/backend-replacement#16]
```
etherdelta_observer_1  | Connection closed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
etherdelta_observer_1  | Task exception was never retrieved
etherdelta_observer_1  | future: <Task finished coro=<SocketIOClient.engineio_ping() done, defined at /usr/src/app/socketio_client.py:89> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)>
etherdelta_observer_1  | Traceback (most recent call last):
etherdelta_observer_1  |   File "/usr/src/app/socketio_client.py", line 96, in engineio_ping
etherdelta_observer_1  |     await self.ws.send(ENGINEIO_PING)
etherdelta_observer_1  |   File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 334, in send
etherdelta_observer_1  |     yield from self.ensure_open()
etherdelta_observer_1  |   File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 470, in ensure_open
etherdelta_observer_1  |     raise ConnectionClosed(self.close_code, self.close_reason)
etherdelta_observer_1  | websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

"it's ED closing connection unexpectedly on us after we ping it."
"the connection will be restarted, but we should probably handle that error a bit more gracefully"

**Comment by freeatnet** [comment]
@JonathonDunford Issue formatting tip: use ``` (triple-backtick) around code or logs to make format it as a code block.
