### ISSUE TITLE
Exception in huey_consumer

### ISSUE THREAD

**Issue by nihalmpatel** [forkdelta/backend-replacement#204]
```
 huey.consumer.Worker ERROR    Unhandled exception in worker thread
huey_consumer_1        | Traceback (most recent call last):
huey_consumer_1        |   File "/usr/local/lib/python3.6/site-packages/huey/consumer.py", line 169, in process_task
huey_consumer_1        |     task_value = self.huey.execute(task)
huey_consumer_1        |   File "/usr/local/lib/python3.6/site-packages/huey/api.py", line 357, in execute
huey_consumer_1        |     result = task.execute()
huey_consumer_1        |   File "/usr/local/lib/python3.6/site-packages/huey/api.py", line 841, in execute
huey_consumer_1        |     return func(*args, **kwargs)
huey_consumer_1        |   File "/usr/src/app/app/lib/threaded_wrap_async.py", line 46, in wrapper
huey_consumer_1        |     return thread_local.loop.run_until_complete(wrapped(*args, **kwargs))
huey_consumer_1        |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
huey_consumer_1        |     return future.result()
huey_consumer_1        |   File "/usr/src/app/app/tasks/update_order.py", line 49, in update_order_by_signature
huey_consumer_1        |     await internal_update_orders_by_signature([order_signature])
huey_consumer_1        |   File "/usr/src/app/app/tasks/update_order.py", line 69, in internal_update_orders_by_signature
huey_consumer_1        |     await bulk_update_orders(orders)
huey_consumer_1        |   File "/usr/src/app/app/tasks/update_order.py", line 178, in bulk_update_orders
huey_consumer_1        |     update_block_number = int(state["blockNumber"])
huey_consumer_1        | KeyError: 'blockNumber'
```

**Comment by freeatnet** [comment]
@nihalmpatel thanks for the report. Can you check what the contents of `state` is when that happens?

**Comment by nihalmpatel** [comment]
@freeatnet I think I am making mistake while running up the order-refresh-service docker setup. Do I have to publish the 3000 port out of the container?

**Comment by freeatnet** [comment]
@nihalmpatel the pythonic backend services (specifically, huey_consumer) must be able to access order refresh service on port 3000 (as `http://order_refresh:3000`), order refresh service should not need to publish port 3000 on the host.

**Comment by nihalmpatel** [comment]
@freeatnet I am using https://github.com/forkdelta/order-refresh-service docker setup without publishing the port 3000. Still the issue occurs.

**Comment by nihalmpatel** [comment]
@freeatnet Sorry I didn't realize that I had a testnet setup running. When I dig into the order-refresh codebase,  I found out the mainnet was coded default so I couldn't be able to run the order-refresh service for testnet without modifying the order-refresh code. For mainnet setup, it works absolutely fine.
