### ISSUE TITLE
Could not connect to postgres server when start docker

### ISSUE THREAD

**Issue by duongvansang** [forkdelta/backend-replacement#213]
When I start apps with command
`docker-compose up` 
but I got this error, it seems postgres could not create user as I set in .env file
redis_1                | 1:M 18 Sep 03:32:32.860 * DB loaded from disk: 0.000 seconds
redis_1                | 1:M 18 Sep 03:32:32.860 * Ready to accept connections
contract_observer_1    | App.App      INFO     Token list refreshed: 838 tokens.
websocket_server_1     | App.App      INFO     Token list refreshed: 838 tokens.
huey_consumer_1        | App.App      INFO     Token list refreshed: 838 tokens.
huey_consumer_1        | Huey is starting
ticker_1               | App.App      INFO     Token list refreshed: 838 tokens.
postgres_1             | 2019-09-18 03:32:37.221 UTC [25] FATAL:  role "root" does not exist
ticker_1               | Traceback (most recent call last):
ticker_1               |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
ticker_1               |     "__main__", mod_spec)
ticker_1               |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
ticker_1               |     exec(code, run_globals)
ticker_1               |   File "/usr/src/app/app/services/ticker.py", line 257, in <module>
ticker_1               |     loop.run_until_complete(main())
ticker_1               |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
ticker_1               |     return future.result()

=====
my .env file:
# This file contains environment variables needed to run this project.
# Copy this file as .env to set the variables for docker-compose.
HUEY_CONCURRENCY=3
POSTGRES_DB=forkdelta
POSTGRES_USER=root
POSTGRES_PASSWORD=root

HTTP_ORDERS_ENDPOINT_SECRET=hello
HTTP_PROVIDER_URL=https://mainnet.infura.io/eN3BAjb0xWsIC4znIKvN

WS_PROVIDER_URL=wss://mainnet.infura.io/ws

# Uncomment the following line to mount your working copy code into containers.
#COMPOSE_FILE=docker-compose.yml:docker-compose.development.yml

**Comment by vitorgamer58** [comment]
i get the same

`role "root" does not exist`

```
root@ubuntu-s-1vcpu-1gb-nyc3-01:~/backend-replacement/etc/nginx/vhost.d# docker-compose run contract_observer alembic upgrade head
WARNING: The POSTGRES_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The WS_PROVIDER_URL variable is not set. Defaulting to a blank string.
WARNING: The POSTGRES_USER variable is not set. Defaulting to a blank string.
WARNING: The POSTGRES_DB variable is not set. Defaulting to a blank string.
WARNING: The HTTP_PROVIDER_URL variable is not set. Defaulting to a blank string.
WARNING: The HTTP_ORDERS_ENDPOINT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The ALLOWED_ORIGIN_SUFFIXES variable is not set. Defaulting to a blank string.
WARNING: The HUEY_CONCURRENCY variable is not set. Defaulting to a blank string.
Starting backendreplacement_postgres_1 ...
Starting backendreplacement_redis_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "root" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.6/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.6/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 70, in <module>
    run_migrations_online()
  File "alembic/env.py", line 58, in run_migrations_online
    with connectable.connect() as connection:
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2206, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2306, in raw_connection
    self.pool.unique_connection, _connection
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  role "root" does not exist

```

**Comment by vitorgamer58** [comment]
i solved runind the comand on /home directory and running this: https://github.com/taigaio/taiga-back/issues/387#issuecomment-117641951
