### ISSUE TITLE
Exception in `update_order`

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/backend-replacement#44]
```
huey_consumer_2        | 2018-02-18T18:09:30.485956776Z huey.consumer.Worker ERROR    Unhandled exception in worker thread
huey_consumer_2        | 2018-02-18T18:09:30.485973637Z Traceback (most recent call last):
huey_consumer_2        | 2018-02-18T18:09:30.485977353Z   File "/usr/local/lib/python3.6/site-packages/huey/consumer.py", line 169, in process_task
huey_consumer_2        | 2018-02-18T18:09:30.485980061Z     task_value = self.huey.execute(task)
huey_consumer_2        | 2018-02-18T18:09:30.485982650Z   File "/usr/local/lib/python3.6/site-packages/huey/api.py", line 357, in execute
huey_consumer_2        | 2018-02-18T18:09:30.485985159Z     result = task.execute()
huey_consumer_2        | 2018-02-18T18:09:30.485987357Z   File "/usr/local/lib/python3.6/site-packages/huey/api.py", line 841, in execute
huey_consumer_2        | 2018-02-18T18:09:30.485989755Z     return func(*args, **kwargs)
huey_consumer_2        | 2018-02-18T18:09:30.485992334Z   File "/usr/src/app/app/lib/threaded_wrap_async.py", line 25, in wrapper
huey_consumer_2        | 2018-02-18T18:09:30.485994478Z     return thread_local.loop.run_until_complete(wrapped(*args, **kwargs))
huey_consumer_2        | 2018-02-18T18:09:30.485997509Z   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
huey_consumer_2        | 2018-02-18T18:09:30.486000123Z     return future.result()
huey_consumer_2        | 2018-02-18T18:09:30.486002471Z   File "/usr/src/app/app/tasks/update_order.py", line 26, in update_order_by_signature
huey_consumer_2        | 2018-02-18T18:09:30.486004699Z     await update_order(order)
huey_consumer_2        | 2018-02-18T18:09:30.486006927Z   File "/usr/src/app/app/tasks/update_order.py", line 93, in update_order
huey_consumer_2        | 2018-02-18T18:09:30.486009059Z     amount_fill = contract.call().amountFilled(*order_args)
huey_consumer_2        | 2018-02-18T18:09:30.486011231Z   File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 834, in call_contract_function
huey_consumer_2        | 2018-02-18T18:09:30.486013500Z     transaction=transaction,
huey_consumer_2        | 2018-02-18T18:09:30.486015648Z   File "/usr/local/lib/python3.6/site-packages/web3/utils/decorators.py", line 17, in _wrapper
huey_consumer_2        | 2018-02-18T18:09:30.486017818Z     return self.method(obj, *args, **kwargs)
huey_consumer_2        | 2018-02-18T18:09:30.486019858Z   File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 695, in _prepare_transaction
huey_consumer_2        | 2018-02-18T18:09:30.486022077Z     fn_kwargs,
huey_consumer_2        | 2018-02-18T18:09:30.486024081Z   File "/usr/local/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner
huey_consumer_2        | 2018-02-18T18:09:30.486035323Z     return force_obj_to_text(fn(*args, **kwargs))
huey_consumer_2        | 2018-02-18T18:09:30.486037463Z   File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 736, in _encode_transaction_data
huey_consumer_2        | 2018-02-18T18:09:30.486039668Z     return add_0x_prefix(cls._encode_abi(fn_abi, fn_arguments, fn_selector))
huey_consumer_2        | 2018-02-18T18:09:30.486041756Z   File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 707, in _encode_abi
huey_consumer_2        | 2018-02-18T18:09:30.486043922Z     ', '.join(argument_types),
huey_consumer_2        | 2018-02-18T18:09:30.486045969Z TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: address, uint256, address, uint256, uint256, uint256, address, uint8, bytes32, bytes32
```

**Comment by mmhh1910** [comment]
Without seeing the order data not possible to debug.

Should I create a pull request that logs out the order and reraises the exception?

**Comment by mmhh1910** [comment]
I accidentially ran into this exception when I injected orders with a user hex string shorter than 42 characters, e.g "0x123456" instead of "0xd270fDc1b2a369f890E9858F09E3D0769B63b526".

We should add validation rules for new orders that check for the length of hex values. Addresses (user, tokenGet,tokenGive) need 20 bytes, r and s 32 bytes.

**Comment by freeatnet** [comment]
@betterdelta Good thought, and we [already do](https://github.com/forkdelta/backend-replacement/blob/master/app/src/order_message_validator.py#L17).

**Comment by mmhh1910** [comment]
I don't see the length check.

**Comment by freeatnet** [comment]
> `is_hex_address(value)` => `bool`
> Return True if the value is a 20 byte hexadecimal encoded string in any of upper/lower/mixed casing, with or without the 0x prefix.
— https://github.com/ethereum/eth-utils#is_hex_addressvalue--bool

**Comment by mmhh1910** [comment]
Ups... right.

Do you think the exception is from before you've added the checks?

**Comment by freeatnet** [comment]
Last time I encountered this exception, something garbled the r, s, v fields: they had weird lengths coming from ED side. Still totally happening, unfortunately.
