### ISSUE TITLE
test backend-replacement, some error occur

### ISSUE THREAD

**Issue by northeastsquare** [forkdelta/backend-replacement#61]
Thank you for your great work. When I run the project with command:
```
$ docker-compose up
the following exception occur, can you give me some hint to solve it, thanks!
huey_consumer_1        | App.App      INFO     Token list refreshed: 823 tokens.
huey_consumer_1        | App.App      INFO     Token list refreshed: 823 tokens.
huey_consumer_1        | App.App      INFO     Token list refreshed: 823 tokens.
huey_consumer_1        | huey.consumer.Worker ERROR    Unhandled exception in worker thread
huey_consumer_1        | Traceback (most recent call last):
huey_consumer_1        |   File "/usr/local/lib/python3.6/site-packages/huey/consumer.py", line 169, in process_task
huey_consumer_1        |     task_value = self.huey.execute(task)
huey_consumer_1        |   File "/usr/local/lib/python3.6/site-packages/huey/api.py", line 357, in execute
huey_consumer_1        |     result = task.execute()
huey_consumer_1        |   File "/usr/local/lib/python3.6/site-packages/huey/api.py", line 841, in execute
huey_consumer_1        |     return func(*args, **kwargs)
huey_consumer_1        |   File "/usr/src/app/app/lib/threaded_wrap_async.py", line 25, in wrapper
huey_consumer_1        |     return thread_local.loop.run_until_complete(wrapped(*args, **kwargs))
huey_consumer_1        |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
huey_consumer_1        |     return future.result()
huey_consumer_1        |   File "/usr/src/app/app/tasks/update_order.py", line 26, in update_order_by_signature
huey_consumer_1        |     await update_order(order)
huey_consumer_1        |   File "/usr/src/app/app/tasks/update_order.py", line 90, in update_order
huey_consumer_1        |     order_args = order_as_args(order)
huey_consumer_1        |   File "/usr/src/app/app/tasks/update_order.py", line 114, in order_as_args
huey_consumer_1        |     order.get("v", 0),
huey_consumer_1        | AttributeError: 'asyncpg.Record' object has no attribute 'get'
huey_consumer_1        | tasks.update_order DEBUG    Update order by signature=0x538f53b35ba1696dfd6c2d221c5e03424fb815b4b2ba8b54cd44ec055d5c4d09
```

**Comment by northeastsquare** [comment]
change some code, fix:
        order["v"],
        #order.get("v", 0),
		order["r"],
        #order.get("r", EMPTY_BYTES32),
		order["s"])
        #order.get("s", EMPTY_BYTES32))
