### ISSUE TITLE
HTTPConnectionPool(host='138.197.160.134', port=8545): Read timed out

### ISSUE THREAD

**Issue by northeastsquare** [forkdelta/backend-replacement#62]
```
ticker_1               | services.ticker DEBUG    {'token_address': '0x55c2a0c171d920843560594de3d6eecc09efc098', 'quote_volume': Decimal('0'), 'base_volume': Decimal('0'), 'last': None, 'ask': Decimal('0.000868'), 'bid': Decimal('0.000010002')}
ticker_1               | Traceback (most recent call last):
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
ticker_1               |     six.raise_from(e, None)
ticker_1               |   File "<string>", line 2, in raise_from
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
ticker_1               |     httplib_response = conn.getresponse()
ticker_1               |   File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
ticker_1               |     response.begin()
ticker_1               |   File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
ticker_1               |     version, status, reason = self._read_status()
ticker_1               |   File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
ticker_1               |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
ticker_1               |   File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
ticker_1               |     return self._sock.recv_into(b)
ticker_1               | socket.timeout: timed out
ticker_1               | 
ticker_1               | During handling of the above exception, another exception occurred:
ticker_1               | 
ticker_1               | Traceback (most recent call last):
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
ticker_1               |     timeout=timeout
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
ticker_1               |     _stacktrace=sys.exc_info()[2])
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
ticker_1               |     raise six.reraise(type(error), error, _stacktrace)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
ticker_1               |     raise value
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
ticker_1               |     chunked=chunked)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
ticker_1               |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
ticker_1               |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
ticker_1               |     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ticker_1               | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='138.197.160.134', port=8545): Read timed out. (read timeout=10)
```

**Comment by northeastsquare** [comment]
change the following solve it:
HTTP_PROVIDER_URL=https://mainnet.infura.io
#HTTP_PROVIDER_URL=http://138.197.160.134:8545/
WS_PROVIDER_URL=ws://mainnet.infura.io
#WS_PROVIDER_URL=ws://138.197.160.134:8546/

**Comment by northeastsquare** [comment]
After the HTTP_PROVIDER_URL WS_PROVIDER_URL change, the problem remains

**Comment by freeatnet** [comment]
@northeastsquare Formatting pro-tip: use triple backticks (```) at the start and the end of a code block or log output :)

You need a Parity Ethereum node for the backend. Unfortunately, we cannot provide one for public use at this time.
